platform :ios, '12.0'

use_frameworks!

target 'NetAnalyser_Example' do
  pod 'NetAnalyser', :path => '../'

  target 'NetAnalyser_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 3.0'
    pod 'Nimble', '~> 8.1'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
