platform :ios, '12.0'

use_frameworks!

target 'NetAnalyser_Example' do
  pod 'NetAnalyser', :path => '../'
  
  target 'NetAnalyser_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.1'
  end

end
